[package]
name = "rust"
version = "0.1.0"
authors = ["Jordan Gregory <gregory.jordan.m@gmail.com>"]
edition = "2018"

[[bin]]
name = "rust_day1"
path = "src/main.rs"

[dependencies]
structopt = "0.3.20"
combinations = "0.1.0"